### ISSUE TITLE
Demo run error

### ISSUE THREAD

**Issue by sunbx** [genievot/oracle-service#1]
Hi,Vitaljeevanjot

![image](https://user-images.githubusercontent.com/8652427/232391053-5e62f0f4-423a-49df-b869-cc6bcf23a9df.png)

Is it wrong for me to use it according to the documentation? How should I use it? Can you write a separate Demo project

**Comment by VitalJeevanjot** [comment]
Hi @sunbx ,

The Ae editor have this bug where it is not producing right tokens for url characters in string, Please try it using JS sdk.

Also to work for the demo, you will need to run the backend from backend folder.
